import React, { useState } from 'react';
import {
  GitBranch,
  Clock,
  User,
  ShieldCheck,
  AlertTriangle,
  ArrowRight,
  CheckCircle2,
  FileText,
  RotateCcw
} from 'lucide-react';
import { useRailway } from '../context/RailwayContext';

export const BlockPlanChangesPage = () => {
  const { currentZone, currentDivision, blockPlans } = useRailway();
  const [selectedPlanId, setSelectedPlanId] = useState('BP-WCR-1024');

  // Multi-version history tracking
  const versionHistory = [
    {
      planId: 'BP-WCR-1024',
      version: 3,
      corridor: 'BPL - SEH',
      section: 'BPL - SEH (Km 12/4 - 18/6)',
      window: '11:30 – 13:30 IST',
      duration: '120 Mins',
      reason: 'Operational conflict: Extended window by 30 mins to permit simultaneous TRD catenary tensioning alongside P-Way tamping.',
      changedBy: 'DOM Sanjay Srivastava',
      changedAt: 'Today, 11:15 IST',
      changes: [
        { field: 'Duration', from: '90 Mins', to: '120 Mins' },
        { field: 'End Time', from: '13:00 IST', to: '13:30 IST' },
        { field: 'Departments', from: 'P-Way + S&T', to: 'P-Way + S&T + TRD (Triple Bundle)' }
      ]
    },
    {
      planId: 'BP-WCR-1024',
      version: 2,
      corridor: 'BPL - SEH',
      section: 'BPL - SEH (Km 12/4 - 14/8)',
      window: '11:30 – 13:00 IST',
      duration: '90 Mins',
      reason: 'Train Conflict: Shifted start time from 11:00 to 11:30 to clear high-priority passenger Train 12002 (Shatabdi Exp).',
      changedBy: 'Chief Controller Rajesh K. Sharma',
      changedAt: 'Today, 09:30 IST',
      changes: [
        { field: 'Start Time', from: '11:00 IST', to: '11:30 IST' },
        { field: 'Train Impact', from: '12002 Regulated 25m', to: '12002 Regulated 12m (Optimal)' }
      ]
    },
    {
      planId: 'BP-WCR-1024',
      version: 1,
      corridor: 'BPL - SEH',
      section: 'BPL - SEH (Km 12/4 - 14/8)',
      window: '11:00 – 12:30 IST',
      duration: '90 Mins',
      reason: 'Initial Automatic Block Optimization schedule generated by RailOpt AI Engine.',
      changedBy: 'RailOpt AI Engine (Autonomous Solver)',
      changedAt: 'Today, 08:00 IST',
      changes: [
        { field: 'Baseline Plan', from: 'None', to: 'Generated v1' }
      ]
    }
  ];

  return (
    <div className="space-y-6 pb-20 w-full max-w-7xl mx-auto selection:bg-red-700 selection:text-white font-sans font-mono text-xs">
      {/* Header */}
      <div className="p-5 rounded-2xl bg-gradient-to-r from-[#070D18] via-[#0A1426] to-[#070D18] border border-blue-900/40 shadow-xl flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 mb-1 text-cyan-400 font-bold uppercase tracking-wider">
            <GitBranch className="w-4 h-4 text-cyan-400" />
            <span>VERSION CONTROL & AUDIT TRAIL • {currentZone} / {currentDivision}</span>
          </div>
          <h1 className="text-2xl font-black text-white">
            CHANGES IN BLOCK PLANS
          </h1>
          <p className="text-slate-400 mt-1">
            Complete immutable version history. Every timing modification, train conflict adjustment, and authorization audit.
          </p>
        </div>

        <div className="flex items-center gap-2">
          <span className="px-3 py-1.5 rounded-xl bg-slate-900 border border-slate-700 text-cyan-300 font-bold">
            TRACKING PLAN: {selectedPlanId}
          </span>
        </div>
      </div>

      {/* Version Timeline Cards */}
      <div className="space-y-4">
        {versionHistory.map((ver, idx) => {
          const isLatest = idx === 0;

          return (
            <div
              key={ver.version}
              className={`p-5 rounded-2xl border transition-all ${
                isLatest
                  ? 'bg-[#0B1528] border-cyan-500/80 shadow-xl shadow-cyan-950/40'
                  : 'bg-[#090F1C] border-slate-800'
              }`}
            >
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pb-3 border-b border-slate-800">
                <div className="flex items-center gap-3">
                  <div className={`w-8 h-8 rounded-lg flex items-center justify-center font-bold text-xs ${
                    isLatest ? 'bg-cyan-950 border border-cyan-400 text-cyan-300' : 'bg-slate-900 text-slate-400'
                  }`}>
                    v{ver.version}
                  </div>
                  <div>
                    <h3 className="font-bold text-white text-sm">
                      {ver.planId} (Version {ver.version})
                    </h3>
                    <span className="text-slate-400 text-[11px]">{ver.section}</span>
                  </div>
                </div>

                <div className="flex items-center gap-3">
                  <span className="px-2.5 py-0.5 rounded bg-slate-900 text-slate-300 border border-slate-700 font-bold">
                    {ver.window} ({ver.duration})
                  </span>
                  {isLatest && (
                    <span className="px-2 py-0.5 rounded bg-emerald-950 text-emerald-300 border border-emerald-600 font-bold text-[10px]">
                      CURRENT ACTIVE VERSION
                    </span>
                  )}
                </div>
              </div>

              {/* Reason & Authorization */}
              <div className="my-3 space-y-1">
                <div className="text-slate-300">
                  <strong className="text-cyan-400">Modification Reason:</strong> {ver.reason}
                </div>
                <div className="text-slate-500 text-[11px] flex items-center gap-3 pt-1">
                  <span>Authorized By: <strong className="text-slate-300">{ver.changedBy}</strong></span>
                  <span>•</span>
                  <span>Timestamp: <strong className="text-slate-300">{ver.changedAt}</strong></span>
                </div>
              </div>

              {/* Diffs */}
              <div className="pt-3 border-t border-slate-800/80">
                <span className="text-[10px] text-slate-500 block uppercase font-bold mb-2">
                  MODIFIED ATTRIBUTES (AUDIT DELTA):
                </span>
                <div className="grid grid-cols-1 sm:grid-cols-3 gap-2">
                  {ver.changes.map((ch, cIdx) => (
                    <div key={cIdx} className="p-2 rounded-lg bg-black/40 border border-slate-800 text-[11px]">
                      <span className="text-slate-500 block text-[10px]">{ch.field}:</span>
                      <span className="line-through text-slate-500 mr-2">{ch.from}</span>
                      <span className="text-emerald-400 font-bold">➔ {ch.to}</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
};
