import React, { useState } from 'react';
import {
  GitBranch, Clock, User, ShieldCheck, AlertTriangle,
  ArrowRight, CheckCircle2, FileText, RotateCcw
} from 'lucide-react';
import { useRailway } from '../context/RailwayContext';

export const BlockPlanChangesPage = () => {
  const { currentZone, currentDivision, blockPlans } = useRailway();
  const [selectedPlanId, setSelectedPlanId] = useState('BP-WCR-1024');

  const [isModalOpen, setIsModalOpen] = useState(false);
  const [modForm, setModForm] = useState({ reason: '', newDuration: '150 Mins', newEndTime: '14:00 IST' });

  const [versionHistory, setVersionHistory] = useState([
    {
      planId: 'BP-WCR-1024', version: 3, corridor: 'BPL - SEH',
      section: 'BPL - SEH (Km 12/4 - 18/6)', window: '11:30 - 13:30 IST', duration: '120 Mins',
      reason: 'Operational conflict: Extended window by 30 mins to permit simultaneous TRD catenary tensioning alongside P-Way tamping.',
      changedBy: 'DOM Sanjay Srivastava', changedAt: 'Today, 11:15 IST',
      changes: [
        { field: 'Duration', from: '90 Mins', to: '120 Mins' },
        { field: 'End Time', from: '13:00 IST', to: '13:30 IST' },
        { field: 'Departments', from: 'P-Way + S&T', to: 'P-Way + S&T + TRD (Triple Bundle)' }
      ]
    },
    {
      planId: 'BP-WCR-1024', version: 2, corridor: 'BPL - SEH',
      section: 'BPL - SEH (Km 12/4 - 14/8)', window: '11:30 - 13:00 IST', duration: '90 Mins',
      reason: 'Train Conflict: Shifted start time from 11:00 to 11:30 to clear high-priority passenger Train 12002 (Shatabdi Exp).',
      changedBy: 'Chief Controller Rajesh K. Sharma', changedAt: 'Today, 09:30 IST',
      changes: [
        { field: 'Start Time', from: '11:00 IST', to: '11:30 IST' },
        { field: 'Train Impact', from: '12002 Regulated 25m', to: '12002 Regulated 12m (Optimal)' }
      ]
    },
    {
      planId: 'BP-WCR-1024', version: 1, corridor: 'BPL - SEH',
      section: 'BPL - SEH (Km 12/4 - 14/8)', window: '11:00 - 12:30 IST', duration: '90 Mins',
      reason: 'Initial Automatic Block Optimization schedule generated by RailOpt AI Engine.',
      changedBy: 'RailOpt AI Engine (Autonomous Solver)', changedAt: 'Today, 08:00 IST',
      changes: [{ field: 'Baseline Plan', from: 'None', to: 'Generated v1' }]
    }
  ]);

  const handleModifySubmit = (e) => {
    e.preventDefault();
    const newVersion = {
      planId: 'BP-WCR-1024',
      version: versionHistory.length + 1,
      corridor: 'BPL - SEH',
      section: 'BPL - SEH (Km 12/4 - 18/6)',
      window: `11:30 - ${modForm.newEndTime}`,
      duration: modForm.newDuration,
      reason: modForm.reason,
      changedBy: 'DOM Sanjay Srivastava', // Or fetch from auth context if needed
      changedAt: 'Today, Just Now',
      changes: [
        { field: 'Duration', from: versionHistory[0].duration, to: modForm.newDuration },
        { field: 'End Time', from: versionHistory[0].window.split(' - ')[1], to: modForm.newEndTime }
      ]
    };
    setVersionHistory([newVersion, ...versionHistory]);
    setIsModalOpen(false);
    setModForm({ reason: '', newDuration: '', newEndTime: '' });
  };

  return (
    <div className="space-y-6 pb-20 w-full max-w-7xl mx-auto selection:bg-[#173B73] selection:text-white font-sans text-xs">

      {/* Header - White + Navy */}
      <div className="rounded-xl overflow-hidden border border-[#D9DEE7] shadow-md bg-white">
        <div className="bg-[#173B73] px-5 py-3 flex flex-col sm:flex-row sm:items-center justify-between gap-2">
          <div className="flex items-center gap-2.5">
            <div className="w-1.5 h-6 rounded-full bg-amber-400 flex-shrink-0" />
            <div>
              <div className="flex items-center gap-2 text-[10px] font-mono font-bold text-blue-200 uppercase tracking-wider mb-0.5">
                <GitBranch className="w-3.5 h-3.5 text-blue-300" />
                <span>VERSION CONTROL &amp; AUDIT TRAIL &bull; {currentZone} / {currentDivision}</span>
              </div>
              <h1 className="text-lg font-black text-white tracking-tight">CHANGES IN BLOCK PLANS</h1>
            </div>
          </div>
          <div className="flex flex-col sm:flex-row items-end sm:items-center gap-3">
            <span className="px-3 py-1.5 rounded-lg bg-[#10274C] border border-blue-600/40 text-blue-300 font-bold text-[10px] font-mono">
              TRACKING: {selectedPlanId}
            </span>
            <button
              onClick={() => setIsModalOpen(true)}
              className="px-4 py-2 rounded-xl bg-blue-600 hover:bg-blue-700 text-white font-bold text-xs flex items-center gap-2 shadow-md transition-colors"
            >
              <RotateCcw className="w-4 h-4" />
              <span>Modify Block Plan</span>
            </button>
          </div>
        </div>
        <div className="px-5 py-3">
          <p className="text-xs text-[#5B6575] font-medium">
            Complete immutable version history. Every timing modification, train conflict adjustment, and authorization audit.
          </p>
        </div>
      </div>

      {/* Version Timeline Cards */}
      <div className="space-y-4">
        {versionHistory.map((ver, idx) => {
          const isLatest = idx === 0;
          return (
            <div
              key={ver.version}
              className={`p-5 rounded-xl border transition-all bg-white ${
                isLatest
                  ? 'border-[#173B73] shadow-md ring-1 ring-[#173B73]/10'
                  : 'border-[#D9DEE7]'
              }`}
            >
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pb-3 border-b border-[#D9DEE7]">
                <div className="flex items-center gap-3">
                  <div className={`w-8 h-8 rounded-lg flex items-center justify-center font-bold text-xs font-mono ${
                    isLatest ? 'bg-[#173B73] text-white' : 'bg-[#F4F6F8] text-[#5B6575] border border-[#D9DEE7]'
                  }`}>
                    v{ver.version}
                  </div>
                  <div>
                    <h3 className="font-bold text-[#172033] text-sm">{ver.planId} (Version {ver.version})</h3>
                    <span className="text-[#5B6575] text-[11px] font-mono">{ver.section}</span>
                  </div>
                </div>

                <div className="flex items-center gap-3">
                  <span className="px-2.5 py-0.5 rounded bg-[#F4F6F8] text-[#172033] border border-[#D9DEE7] font-bold font-mono">
                    {ver.window} ({ver.duration})
                  </span>
                  {isLatest && (
                    <span className="px-2 py-0.5 rounded bg-emerald-50 text-[#168A55] border border-emerald-200 font-bold text-[10px]">
                      CURRENT ACTIVE VERSION
                    </span>
                  )}
                </div>
              </div>

              <div className="my-3 space-y-1">
                <div className="text-[#172033]">
                  <strong className="text-[#173B73]">Modification Reason:</strong> {ver.reason}
                </div>
                <div className="text-[#5B6575] text-[11px] flex items-center gap-3 pt-1 font-mono">
                  <span>Authorized By: <strong className="text-[#172033]">{ver.changedBy}</strong></span>
                  <span>&bull;</span>
                  <span>Timestamp: <strong className="text-[#172033]">{ver.changedAt}</strong></span>
                </div>
              </div>

              <div className="pt-3 border-t border-[#D9DEE7]">
                <span className="text-[10px] text-[#5B6575] block uppercase font-bold mb-2 font-mono">
                  MODIFIED ATTRIBUTES (AUDIT DELTA):
                </span>
                <div className="grid grid-cols-1 sm:grid-cols-3 gap-2">
                  {ver.changes.map((ch, cIdx) => (
                    <div key={cIdx} className="p-2 rounded-lg bg-[#F4F6F8] border border-[#D9DEE7] text-[11px] font-mono">
                      <span className="text-[#5B6575] block text-[10px] font-bold uppercase">{ch.field}:</span>
                      <span className="line-through text-[#5B6575] mr-2">{ch.from}</span>
                      <span className="text-[#168A55] font-bold">&#x279C; {ch.to}</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          );
        })}
      </div>

      {/* Modification Modal */}
      {isModalOpen && (
        <div className="fixed inset-0 z-50 bg-black/60 backdrop-blur-sm flex items-center justify-center p-4">
          <div className="w-full max-w-lg bg-white border border-[#D9DEE7] rounded-xl shadow-xl p-6 font-mono text-xs space-y-4">
            <div className="flex items-center justify-between pb-3 border-b border-[#D9DEE7]">
              <h3 className="text-base font-bold text-[#173B73] flex items-center gap-2">
                <RotateCcw className="w-5 h-5" />
                MODIFY BLOCK PLAN {selectedPlanId}
              </h3>
              <button onClick={() => setIsModalOpen(false)} className="text-[#5B6575] hover:text-[#172033]">
                ✕
              </button>
            </div>
            
            <form onSubmit={handleModifySubmit} className="space-y-4">
              <div>
                <label className="text-[#172033] font-bold block mb-1">Reason for Modification</label>
                <textarea
                  required
                  rows={2}
                  value={modForm.reason}
                  onChange={(e) => setModForm({ ...modForm, reason: e.target.value })}
                  placeholder="e.g. Unforeseen track conditions requiring extended block..."
                  className="w-full py-2 px-3 bg-[#F4F6F8] border border-[#D9DEE7] rounded-lg text-[#172033] focus:outline-none focus:border-[#173B73]"
                />
              </div>
              
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="text-[#172033] font-bold block mb-1">New Duration</label>
                  <input
                    required
                    type="text"
                    value={modForm.newDuration}
                    onChange={(e) => setModForm({ ...modForm, newDuration: e.target.value })}
                    placeholder="e.g. 150 Mins"
                    className="w-full py-2 px-3 bg-[#F4F6F8] border border-[#D9DEE7] rounded-lg text-[#172033] focus:outline-none focus:border-[#173B73]"
                  />
                </div>
                <div>
                  <label className="text-[#172033] font-bold block mb-1">New End Time</label>
                  <input
                    required
                    type="text"
                    value={modForm.newEndTime}
                    onChange={(e) => setModForm({ ...modForm, newEndTime: e.target.value })}
                    placeholder="e.g. 14:00 IST"
                    className="w-full py-2 px-3 bg-[#F4F6F8] border border-[#D9DEE7] rounded-lg text-[#172033] focus:outline-none focus:border-[#173B73]"
                  />
                </div>
              </div>
              
              <div className="pt-3 border-t border-[#D9DEE7] flex justify-end gap-3">
                <button
                  type="button"
                  onClick={() => setIsModalOpen(false)}
                  className="px-4 py-2 rounded-lg border border-[#D9DEE7] text-[#5B6575] font-bold hover:bg-[#F4F6F8]"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="px-4 py-2 rounded-lg bg-[#C62828] hover:bg-[#B71C1C] text-white font-bold flex items-center gap-2 shadow-sm"
                >
                  <CheckCircle2 className="w-4 h-4" />
                  Confirm Modification
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

    </div>
  );
};
