package com.railopt.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;

/**
 * Structured explanation response for a validated AI block plan.
 * Generated by Gemini AI (or the deterministic rule engine fallback).
 *
 * SAFETY GUARANTEE:
 * This DTO is strictly advisory and informational. It contains no commands,
 * operational decisions, approvals, or modifications to railway assets.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class BlockPlanExplanationResponse {

    private String planId;
    private String corridorName;
    private String trackLine;
    private LocalDate scheduledDate;
    private String recommendedWindow;

    /** High-level operational summary */
    private String summary;

    /** Bullet points detailing why this specific window was chosen */
    private List<String> whySelected;

    /** Details on train traffic throughput and regulation buffer */
    private String trafficImpact;

    /** Details on bundled departmental tasks and track possession benefits */
    private String maintenanceImpact;

    /** Identified conflict points and how they are resolved/mitigated */
    private List<String> conflicts;

    /** Operational rationale for optimization confidence score */
    private String confidenceExplanation;

    /** Practical operational notes for Section & Chief Controllers */
    private List<String> operationalNotes;

    /** Origin: "GEMINI" or "DETERMINISTIC" */
    private String explanationSource;

    /** Model used (e.g. "gemini-3.6-flash" or "deterministic-rule-engine") */
    private String modelUsed;

    /**
     * Mandatory safety banner:
     * "RailOpt AI selected this block using deterministic optimization. Gemini generated the explanation."
     */
    @Builder.Default
    private String safetyNotice = "RailOpt AI selected this block using deterministic optimization. Gemini generated the explanation.";

    @Builder.Default
    private LocalDateTime generatedAt = LocalDateTime.now();
}
